name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true
        default: "com.firsttouchgames.dls7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        # Sửa thông tin module
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        # Thay package name vào code C++
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        # Ép Gradle dùng đúng NDK có sẵn trong máy ảo GitHub để không lỗi đường dẫn
        ./gradlew :module:assembleRelease -Pandroid.ndkDirectory=$ANDROID_SDK_ROOT/ndk-bundle

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper
        path: out/*.zip
